### ISSUE TITLE
Excessive heating of shift register U4

### ISSUE THREAD

**Issue by mr-sneezy** [gztproject/NixieClock#2]
Issue: 
After finally getting time to assemble my build of this project I find that chip U4 is running at over 60-70C after a minute or so.

Cause:
Design omission in U4 connection to the four MPSA42 bipolar transistors that control the neon decimal point indicators.

Solution:
Add series current limiting resistors (as is normal practice) to the U4 logic output to transistor base.

Implementation:
As I got five boards made already, the easiest fix is to remove the transistors and refit with the base leg in the air, and put a 1Kohm resistor in the board base leg hole, and connect in the air to the transistor base leg. 
U4 now runs at normal safe temperature. 
(A bipolar transistor base-emitter junction behaves like a forward biased diode, pulling the source down to around 0.6V, the U4 logic outputs were being dragged down and causing maximum chip drive current on the four used outputs.)

**Comment by gztproject** [comment]
I'm not sure why I omitted the resistors in the first place, but this is definitely a big oversight. As mentioned this puts excessive strain on U4 and also on the 7805 regulator, U1. Not to talk about excessive power consumption...

Will fix the PCB files to include the resistors.

**Comment by gztproject** [comment]
Fixed
